### PR TITLE
Option menu

### PR DESCRIPTION
**Pull request by thangn2703**
Setting menu for the game. Using copyrighted music now, leave some input and it is easy to change

### CODE REVIEW

**Comment by Aiz0** [comment]
yeah please don't use copyrighted music.
It works and that's good but why did you change the shop sprite on main menu?
Also it's good that you added a button back to menu in the shop(assuming you did that) but why in this pull request?

Music is way too loud at the moment.

**Comment by Aiz0** [comment]
Also fix merge conflicts

**Comment by thangn2703** [comment]
didn't change the shop sprite, basically build on the old version that does not include shop sprite button. updatiing with main now, The back button in the shop menu can be added later in a new branch then. (Added here because didn't have an option to test going from shop to menu when testing the music)

**Comment by thangn2703** [comment]
Reduce the volume of the background music and increase the effect sounds volume

**Review by Aiz0 — APPROVED** [review]
Looks Good now

**Pull request merged**
